
version: 2
executorType: machine

containerInfo:
  - image: 'docker:1.13-git'

stages:
  build:
    workDir: ~/dobi
    steps:
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: 'docker version'
      # TODO: load cache
      - type: shell
        shell: /bin/sh
        command: 'script/ci-deps'
      - type: shell
        shell: /bin/sh
      # TODO: parallel
        command: 'script/ci-run'

#general:
#  branches:
#    ignore: [gh-pages]

#dependencies:
#  override: [script/ci-deps]
#  cache_directories: [vendor]

#test:
#  override:
#    - script/ci-run:
#        parallel: true
#
#deployment:
#  release:
#    tag: /v[0-9]+(\.[0-9]+)*/
#    commands:
#      - 'docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS'
#      - 'DOBI_EXEC_ID=release circle/dobi release'
